import "../../app/globals.css";
import type { Metadata } from "next";

import { Locale, i18n } from "@/i18n.config";
import { Languages } from "./Models/languages.enum";

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { lang: Locale };
}) {
  return (
    <html lang={params.lang} dir={params.lang == Languages.FARSI ? "rtl" : "ltr"}>
      <head>
       
      </head>
      <body suppressHydrationWarning={true}>
       
        {children}
      </body>
    </html>
  );
}
